### ISSUE TITLE
fix(netexec): netifaces build failure on Alpine Linux with Python 3.13

### ISSUE THREAD

**Issue by Megafredo** [OpenAEV-Platform/injectors#448]
## Description
The NetExec injector fails to build on Alpine Linux with Python 3.13.

The build fails while compiling the `netifaces` dependency. NetExec and its other dependencies are successfully built, but netifaces fails during the compilation of its native C extension.

DETAILS ERROR: `Failed building wheel for netifaces`
```
40.41       building 'netifaces' extension
40.41       gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -DNETIFACES_VERSION=0.11.0 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/local/include/python3.13 -c netifaces.c -o build/temp.linux-x86_64-cpython-313/netifaces.o
40.41       netifaces.c: In function 'gateways':
40.41       netifaces.c:1808:9: error: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
40.41        1808 |         NULL,
40.41             |         ^~~~
40.41       netifaces.c:1808:9: note: (near initialization for 'msghdr.__pad1')
40.41       netifaces.c:1843:33: warning: comparison of integer expressions of different signedness: '__u32' {aka 'unsigned int'} and 'int' [-Wsign-compare]
40.41        1843 |         if (pmsg->hdr.nlmsg_seq != seq || pmsg->hdr.nlmsg_pid != sanl.nl_pid)
40.41             |                                 ^~
40.41       error: Command '['gcc', '-fno-strict-overflow', '-Wsign-compare', '-DNDEBUG', '-g', '-O3', '-Wall', '-fPIC', '-DNETIFACES_VERSION=0.11.0', '-DHAVE_GETIFADDRS=1', '-DHAVE_GETNAMEINFO=1', '-DHAVE_NETPACKET_PACKET_H=1', '-DHAVE_LINUX_ATM_H=1', '-DHAVE_LINUX_LLC_H=1', '-DHAVE_LINUX_TIPC_H=1', '-DHAVE_SOCKADDR_IN=1', '-DHAVE_SOCKADDR_IN6=1', '-DHAVE_SOCKADDR_UN=1', '-DHAVE_SOCKADDR_LL=1', '-DHAVE_SOCKADDR_ATMPVC=1', '-DHAVE_SOCKADDR_ATMSVC=1', '-DHAVE_SOCKADDR_LLC=1', '-DHAVE_PF_NETLINK=1', '-I/usr/local/include/python3.13', '-c', 'netifaces.c', '-o', 'build/temp.linux-x86_64-cpython-313/netifaces.o']' returned non-zero exit status 1.
40.41       [end of output]
40.41
40.41   note: This error originates from a subprocess, and is likely not a problem with pip.
40.41   ERROR: Failed building wheel for netifaces
...
60.47 Successfully built netexec certipy-ad impacket pynfsclient aardwolf arc4 python-libnmap
60.47 Failed to build netifaces
60.47 error: failed-wheel-build-for-install
60.47
60.47 × Failed to build installable wheels for some pyproject.toml based projects
60.47 ╰─> netifaces
```

The workaround is to disable the `-Wint-conversion` check when installing NetExec:

`RUN CFLAGS="-Wno-int-conversion" pip install --no-cache-dir git+https://github.com/Pennyw0rth/NetExec.git`

This allows the netifaces extension to compile by treating the -Wint-conversion diagnostic as a warning instead of an error.

## Expected output

The NetExec dependency and the OpenAEV NetExec injector should be successfully installed and the Docker image should be built.

## Actual output

The Docker build fails because pip cannot build an installable wheel for netifaces:

ERROR: Failed building wheel for netifaces

× Failed to build installable wheels for some pyproject.toml based projects
╰─> netifaces

## Additional information

Thanks to @guzmud for the more in-depth investigation.
You will find the details below:

`msghdr` has a parameter initialized with `NULL`.
 
`NULL` represents a null pointer (https://man7.org/linux/man-pages/man3/null.3const.html), and the source of the error message, but let's see how it's used, and thus focus on how msghdr is used.
 
The interesting part is that `msghdr` is passed to recvmsg() immediately afterwards. The `recvmsg()` documentation (https://linux.die.net/man/2/recvmsg) describes the format of msghdr; the last three elements, which are set to `NULL`, 0, and 0 here, are used for control functions related to `cmsg`.
 
There does not appear to be any use of `cmsg` or control functions in the netifaces codebase (a search within the codebase returned no results). In addition, since the value following `NULL` is set to 0, the associated buffer has a size of zero. Therefore, even if the value were a valid pointer to a buffer, its size would still be explicitly set to 0, unlike a case where a buffer and its actual size would be provided, for example `&msg_control_buffer` together with `sizeof(msg_control_buffer)`.
 
The `-Wint-conversion` error therefore appears to concern a field that is not used by the relevant code path. Disabling this specific check would turn the compilation error into a warning without being expected to affect the functionality of the code, since the affected control-message fields are not used and the associated buffer size is set to 0.
 
TL;DR: The error can be treated as a compiler type-checking issue affecting an unused control-message field. Disabling `-Wint-conversion` appears to be a suitable workaround for this specific build failure.
